### ISSUE TITLE
Urgent issue

### ISSUE THREAD

**Issue by gajalakshmi2901** [data-platform-hq/terraform-azurerm-automation-runbook#3]
│ Invalid value for "path" parameter: no file exists at "../scripts/vm_stop.tftpl"; this function works only with files that 
│ are distributed as part of the configuration source code, so if this file will be created by a resource in this
│ configuration you must instead obtain this result from an attribute of that resource. Im getting the following error .pls look into this asap

**Comment by owlleg6** [comment]
@gajalakshmi2901 Hello, you can update example with value that leads to your own script within repository or just pass script content using EOT into 'content' parameter of 'runbook' object. Thanks, please write back if this issue is still relevant.
